all:
  vars:
    ansible_user: root
    ansible_password: toor
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  children:
    masters:
      hosts:
        lap-k8s-master-01:
          ansible_host: 192.168.0.150
    workers:
      hosts:
        lap-k8s-worker-01:
          ansible_host: 192.168.0.151
        lap-k8s-worker-02:
          ansible_host: 192.168.0.152
    k8s_cluster:
      children:
        masters:
        workers:
